export const types = [
  {
    id: 1,
    type: "Normal",
    strengths: ["None"],
    weaknesses: ["Fighting"],
  },
  {
    id: 2,
    type: "Fire",
    strengths: ["Grass", "Ice", "Bug", "Steel"],
    weaknesses: ["Fire", "Water", "Rock", "Dragon"],
  },
  {
    id: 3,
    type: "Water",
    strengths: ["Fire", "Ground", "Rock"],
    weaknesses: ["Water", "Grass", "Dragon"],
  },
  {
    id: 4,
    type: "Electric",
    strengths: ["Water", "Flying"],
    weaknesses: ["Electric", "Grass", "Dragon"],
  },
  {
    id: 5,
    type: "Grass",
    strengths: ["Water", "Ground", "Rock"],
    weaknesses: ["Fire", "Grass", "Poison", "Flying", "Bug", "Dragon"],
  },
  {
    id: 6,
    type: "Ice",
    strengths: ["Grass", "Ground", "Flying", "Dragon"],
    weaknesses: ["Fire", "Water", "Ice", "Steel"],
  },
  {
    id: 7,
    type: "Fighting",
    strengths: ["Normal", "Ice", "Rock", "Dark", "Steel"],
    weaknesses: ["Poison", "Flying", "Psychic", "Bug", "Fairy"],
  },
  {
    id: 8,
    type: "Poison",
    strengths: ["Grass", "Fairy"],
    weaknesses: ["Poison", "Ground", "Rock", "Ghost"],
  },
  {
    id: 9,
    type: "Ground",
    strengths: ["Fire", "Electric", "Poison", "Rock", "Steel"],
    weaknesses: ["Grass", "Bug"],
  },
  {
    id: 10,
    type: "Flying",
    strengths: ["Grass", "Fighting", "Bug"],
    weaknesses: ["Electric", "Rock", "Steel"],
  },
  {
    id: 11,
    type: "Psychic",
    strengths: ["Fighting", "Poison"],
    weaknesses: ["Psychic", "Steel"],
  },
  {
    id: 12,
    type: "Bug",
    strengths: ["Grass", "Psychic", "Dark"],
    weaknesses: [
      "Fire",
      "Fighting",
      "Flying",
      "Poison",
      "Ghost",
      "Steel",
      "Fairy",
    ],
  },
  {
    id: 13,
    type: "Rock",
    strengths: ["Fire", "Ice", "Flying", "Bug"],
    weaknesses: ["Fighting", "Ground", "Steel"],
  },
  {
    id: 14,
    type: "Ghost",
    strengths: ["Psychic", "Ghost"],
    weaknesses: ["Dark"],
  },
  {
    id: 15,
    type: "Dragon",
    strengths: ["Dragon"],
    weaknesses: ["Steel", "Fairy"],
  },
  {
    id: 16,
    type: "Dark",
    strengths: ["Psychic", "Ghost"],
    weaknesses: ["Fighting", "Dark", "Fairy"],
  },
  {
    id: 17,
    type: "Steel",
    strengths: ["Ice", "Rock", "Fairy"],
    weaknesses: ["Fire", "Water", "Electric", "Steel"],
  },
  {
    id: 18,
    type: "Fairy",
    strengths: ["Fighting", "Dragon", "Dark"],
    weaknesses: ["Poison", "Steel"],
  },
];
